apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.json: |
    {
      "tunnels" : [
        {
          "hostname": "example.org",
          "targetPort": 80,
          "targetHost": "93.184.216.34",
          "cookie": "__Host-socketzero-authservice-session-id-cookie"
        },
        {
          "hostname": "redis.apps.radiusmethod.io",
          "targetPort": 6379,
          "targetHost": "socketzero-redis-master.socketzero.svc.cluster.local",
          "cookie": "__Host-socketzero-authservice-session-id-cookie"
        },
        {
          "hostname": "rdp.apps.radiusmethod.io",
          "targetPort": 3389,
          "targetHost": "rdp.rdp.svc.cluster.local",
          "cookie": "__Host-socketzero-authservice-session-id-cookie"
        },
        {
          "hostname": "ssh.apps.radiusmethod.io",
          "targetPort": 2222,
          "targetHost": "ssh.ssh.svc.cluster.local",
          "cookie": "__Host-socketzero-authservice-session-id-cookie"
        },
        {
          "hostname": "mariadb.apps.radiusmethod.io",
          "targetPort": 3306,
          "targetHost": "mariadb.mariadb.svc.cluster.local",
          "cookie": "__Host-socketzero-authservice-session-id-cookie"
        }
      ]
    }
