apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-license
type: Opaque
stringData:
  SOCKETZERO_LICENSE: '{{ .Values.license.key | default "" }}'
  SOCKETZERO_ORGANIZATION: '{{ .Values.license.organization | default "" }}'
